

trigger: none

pr: none

resources:
  pipelines:
  - pipeline: ci
    source: notebooks_ci_bo
    # trigger: 
    #   branches:
    #   - master

stages:
- stage: deploy_to_test
  displayName: 'Deploy notebooks'
  variables:
  - group: mdwdo-dbx-nd-test-bo
  jobs:
  - template: ../../devops/templates/jobs/deploy-notebooks-job.yml
    parameters:
      environmentName: 'TEST'
      databricksDomain: '$(databricksDomain)'
      databricksToken: '$(databricksToken)'
      databricksNotebookPath: '$(databricksNotebookPath)'
      
  # - template: ../../devops/templates/jobs/integration-tests-job.yml
  #   parameters:
  #     environmentName: 'TEST'
  #     databricksDomain: '$(databricksDomain)'
  #     databricksToken: '$(databricksToken)'
  #     databricksNotebookPath: '$(databricksNotebookPath)'
  #     databricksClusterId: '$(databricksClusterId)'