trigger: none

pool:
  name: Hosted Ubuntu 1604

variables:
  basePath: 'single_tech_samples/databricks/sample4_ci_cd'

steps:
# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(basePath)/multi-notebooks/notebooks'
#     ArtifactName: 'notebooks'
#   displayName: 'Publish Databricks notebooks'

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(basePath)/multi-notebooks/tests'
#     ArtifactName: 'tests'
#   displayName: 'Publish Databricks notebooks'

# - task: PublishPipelineArtifact@1
#   inputs:
#     targetPath: '$(basePath)/devops/scripts'
#     ArtifactName: 'devops_scripts'
#   displayName: 'Publish DevOps Scripts'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(basePath)/multi-notebooks/notebooks'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/notebooks

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(basePath)/multi-notebooks/tests'
    contents: '**'
    targetFolder: $(Build.ArtifactStagingDirectory)/tests

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true # Optional
    artifactName: notebooks
  displayName: 'Publish DevOps Scripts'